# PhotoPainter app state
window_min=1024x768
last_window_size=1200x943
last_window_position=2765x81
image_target_size=800x480
image_quality=90
orientation=landscape
fill_mode=blur
target_device=acep
enhancer_edge=False
enhancer_smooth=False
enhancer_sharpen=False
grid_color=#00ff00
pic_folder_on_device=pic
state_suffix=_ppcrop.txt
save_filelist=True
exit_after_last_image=False
save_canvas_zoom=True
canvas_zoom=1.0
gallery_show_landscape=True
gallery_show_portrait=True
gallery_show_unprocessed=False